apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pandemi-cluster-role
rules:
  - apiGroups:
      {{- range .Values.clusterRole.apiGroups }}
      - "{{ . }}"
      {{- end }}
    resources:
      {{- range .Values.clusterRole.resources }}
      - "{{ . }}"
      {{- end }}
    verbs:
      {{- range .Values.clusterRole.verbs }}
      - "{{ . }}"
      {{- end }}