apiVersion: apps/v1
kind: Deployment
metadata:
  name: pandemi-deployment
  labels:
    app: pandemi
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: pandemi
  template:
    metadata:
      labels:
        app: pandemi
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
        - name: pandemi
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace