apiVersion: apps/v1
kind: Deployment
metadata:
  name: pandemi-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: pandemi
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: pandemi
  template:
    metadata:
      labels:
        app: pandemi
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: pandemi
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}