apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: magneto-cluster-role
rules:
  - apiGroups:
      - ""
    resources:
      - "configmaps"
      - "secrets"
      - "namespaces"
      - "nodes"
    verbs:
      - "get"
      - "watch"
      - "list"
  - apiGroups:
      - ""
    resources:
      - "pods"
      - "pods/eviction"
    verbs:
      - "get"
      - "watch"
      - "list"
      - "create"
      - "update"
      - "delete"
      - "patch"
      - "eviction"