apiVersion: apps/v1
kind: Deployment
metadata:
  name: magneto
  labels:
    app: magneto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: magneto
  template:
    metadata:
      name: magneto
      labels:
        app: magneto
    spec:
      serviceAccountName: magneto-service-account
      automountServiceAccountToken: true
      containers:
      - name: magneto
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
          - configMapRef:
              name:  magneto-config
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP